package communicate;

/**
* communicate/ICommunicateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Sunday, November 8, 2020 4:59:29 PM EST
*/

public final class ICommunicateHolder implements org.omg.CORBA.portable.Streamable
{
  public communicate.ICommunicate value = null;

  public ICommunicateHolder ()
  {
  }

  public ICommunicateHolder (communicate.ICommunicate initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = communicate.ICommunicateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    communicate.ICommunicateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return communicate.ICommunicateHelper.type ();
  }

}
