package communicate;


/**
* communicate/ICommunicateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Tuesday, October 13, 2020 11:47:16 PM EDT
*/

abstract public class ICommunicateHelper
{
  private static String  _id = "IDL:communicate/ICommunicate:1.0";

  public static void insert (org.omg.CORBA.Any a, communicate.ICommunicate that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static communicate.ICommunicate extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (communicate.ICommunicateHelper.id (), "ICommunicate");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static communicate.ICommunicate read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ICommunicateStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, communicate.ICommunicate value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static communicate.ICommunicate narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof communicate.ICommunicate)
      return (communicate.ICommunicate)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      communicate._ICommunicateStub stub = new communicate._ICommunicateStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static communicate.ICommunicate unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof communicate.ICommunicate)
      return (communicate.ICommunicate)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      communicate._ICommunicateStub stub = new communicate._ICommunicateStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
