package communicate.ICommunicatePackage;


/**
* communicate/ICommunicatePackage/IncorrectUserRoleException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Monday, October 19, 2020 5:33:33 PM EDT
*/

public final class IncorrectUserRoleException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public IncorrectUserRoleException ()
  {
    super(IncorrectUserRoleExceptionHelper.id());
  } // ctor

  public IncorrectUserRoleException (String _reason)
  {
    super(IncorrectUserRoleExceptionHelper.id());
    reason = _reason;
  } // ctor


  public IncorrectUserRoleException (String $reason, String _reason)
  {
    super(IncorrectUserRoleExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class IncorrectUserRoleException
