package communicate.ICommunicatePackage;

/**
* communicate/ICommunicatePackage/ItemOutOfStockExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Friday, October 16, 2020 7:02:15 PM EDT
*/

public final class ItemOutOfStockExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public communicate.ICommunicatePackage.ItemOutOfStockException value = null;

  public ItemOutOfStockExceptionHolder ()
  {
  }

  public ItemOutOfStockExceptionHolder (communicate.ICommunicatePackage.ItemOutOfStockException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = communicate.ICommunicatePackage.ItemOutOfStockExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    communicate.ICommunicatePackage.ItemOutOfStockExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return communicate.ICommunicatePackage.ItemOutOfStockExceptionHelper.type ();
  }

}
