package communicate.ICommunicatePackage;

/**
* communicate/ICommunicatePackage/ItemWasNeverPurchasedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Friday, October 16, 2020 7:02:15 PM EDT
*/

public final class ItemWasNeverPurchasedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public communicate.ICommunicatePackage.ItemWasNeverPurchasedException value = null;

  public ItemWasNeverPurchasedExceptionHolder ()
  {
  }

  public ItemWasNeverPurchasedExceptionHolder (communicate.ICommunicatePackage.ItemWasNeverPurchasedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = communicate.ICommunicatePackage.ItemWasNeverPurchasedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    communicate.ICommunicatePackage.ItemWasNeverPurchasedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return communicate.ICommunicatePackage.ItemWasNeverPurchasedExceptionHelper.type ();
  }

}
