package communicate.ICommunicatePackage;


/**
* communicate/ICommunicatePackage/ManagerItemPriceMismatchException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Sunday, November 8, 2020 4:59:29 PM EST
*/

public final class ManagerItemPriceMismatchException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ManagerItemPriceMismatchException ()
  {
    super(ManagerItemPriceMismatchExceptionHelper.id());
  } // ctor

  public ManagerItemPriceMismatchException (String _reason)
  {
    super(ManagerItemPriceMismatchExceptionHelper.id());
    reason = _reason;
  } // ctor


  public ManagerItemPriceMismatchException (String $reason, String _reason)
  {
    super(ManagerItemPriceMismatchExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ManagerItemPriceMismatchException
