package communicate.ICommunicatePackage;

/**
* communicate/ICommunicatePackage/ManagerRemoveBeyondQuantityExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Sunday, November 8, 2020 4:59:29 PM EST
*/

public final class ManagerRemoveBeyondQuantityExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public communicate.ICommunicatePackage.ManagerRemoveBeyondQuantityException value = null;

  public ManagerRemoveBeyondQuantityExceptionHolder ()
  {
  }

  public ManagerRemoveBeyondQuantityExceptionHolder (communicate.ICommunicatePackage.ManagerRemoveBeyondQuantityException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = communicate.ICommunicatePackage.ManagerRemoveBeyondQuantityExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    communicate.ICommunicatePackage.ManagerRemoveBeyondQuantityExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return communicate.ICommunicatePackage.ManagerRemoveBeyondQuantityExceptionHelper.type ();
  }

}
