package communicate.ICommunicatePackage;

/**
* communicate/ICommunicatePackage/ManagerItemPriceMismatchExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Monday, October 19, 2020 5:33:33 PM EDT
*/

public final class ManagerItemPriceMismatchExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public communicate.ICommunicatePackage.ManagerItemPriceMismatchException value = null;

  public ManagerItemPriceMismatchExceptionHolder ()
  {
  }

  public ManagerItemPriceMismatchExceptionHolder (communicate.ICommunicatePackage.ManagerItemPriceMismatchException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = communicate.ICommunicatePackage.ManagerItemPriceMismatchExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    communicate.ICommunicatePackage.ManagerItemPriceMismatchExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return communicate.ICommunicatePackage.ManagerItemPriceMismatchExceptionHelper.type ();
  }

}
