package communicate.ICommunicatePackage;


/**
* communicate/ICommunicatePackage/ManagerRemoveNonExistingItemException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Friday, October 16, 2020 7:02:15 PM EDT
*/

public final class ManagerRemoveNonExistingItemException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ManagerRemoveNonExistingItemException ()
  {
    super(ManagerRemoveNonExistingItemExceptionHelper.id());
  } // ctor

  public ManagerRemoveNonExistingItemException (String _reason)
  {
    super(ManagerRemoveNonExistingItemExceptionHelper.id());
    reason = _reason;
  } // ctor


  public ManagerRemoveNonExistingItemException (String $reason, String _reason)
  {
    super(ManagerRemoveNonExistingItemExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ManagerRemoveNonExistingItemException
