package communicate.ICommunicatePackage;

/**
* communicate/ICommunicatePackage/ManagerRemoveNonExistingItemExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Monday, October 19, 2020 5:33:33 PM EDT
*/

public final class ManagerRemoveNonExistingItemExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public communicate.ICommunicatePackage.ManagerRemoveNonExistingItemException value = null;

  public ManagerRemoveNonExistingItemExceptionHolder ()
  {
  }

  public ManagerRemoveNonExistingItemExceptionHolder (communicate.ICommunicatePackage.ManagerRemoveNonExistingItemException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = communicate.ICommunicatePackage.ManagerRemoveNonExistingItemExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    communicate.ICommunicatePackage.ManagerRemoveNonExistingItemExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return communicate.ICommunicatePackage.ManagerRemoveNonExistingItemExceptionHelper.type ();
  }

}
