package communicate.ICommunicatePackage;


/**
* communicate/ICommunicatePackage/NotEnoughFundsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Sunday, November 8, 2020 4:59:29 PM EST
*/

public final class NotEnoughFundsException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NotEnoughFundsException ()
  {
    super(NotEnoughFundsExceptionHelper.id());
  } // ctor

  public NotEnoughFundsException (String _reason)
  {
    super(NotEnoughFundsExceptionHelper.id());
    reason = _reason;
  } // ctor


  public NotEnoughFundsException (String $reason, String _reason)
  {
    super(NotEnoughFundsExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NotEnoughFundsException
