package communicate.ICommunicatePackage;

/**
* communicate/ICommunicatePackage/ReturnPolicyExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Monday, October 19, 2020 5:33:33 PM EDT
*/

public final class ReturnPolicyExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public communicate.ICommunicatePackage.ReturnPolicyException value = null;

  public ReturnPolicyExceptionHolder ()
  {
  }

  public ReturnPolicyExceptionHolder (communicate.ICommunicatePackage.ReturnPolicyException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = communicate.ICommunicatePackage.ReturnPolicyExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    communicate.ICommunicatePackage.ReturnPolicyExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return communicate.ICommunicatePackage.ReturnPolicyExceptionHelper.type ();
  }

}
