package communicate.ICommunicatePackage;


/**
* communicate/ICommunicatePackage/ReturnPolicyException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ICommunicate.idl
* Friday, October 16, 2020 7:02:15 PM EDT
*/

public final class ReturnPolicyException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ReturnPolicyException ()
  {
    super(ReturnPolicyExceptionHelper.id());
  } // ctor

  public ReturnPolicyException (String _reason)
  {
    super(ReturnPolicyExceptionHelper.id());
    reason = _reason;
  } // ctor


  public ReturnPolicyException (String $reason, String _reason)
  {
    super(ReturnPolicyExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ReturnPolicyException
